// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkSystemIncludes.h"
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern "C" void real_initvtkSlicerRegistrationModuleLogicPython(const char *modulename);

extern  "C" { VTK_ABI_EXPORT void initvtkSlicerRegistrationModuleLogicPython(); }

void initvtkSlicerRegistrationModuleLogicPython()
{
  static const char modulename[] = "vtkSlicerRegistrationModuleLogicPython";
  real_initvtkSlicerRegistrationModuleLogicPython(modulename);
}

extern  "C" { VTK_ABI_EXPORT void initlibvtkSlicerRegistrationModuleLogicPython(); }

void initlibvtkSlicerRegistrationModuleLogicPython()
{
  static const char modulename[] = "libvtkSlicerRegistrationModuleLogicPython";
  real_initvtkSlicerRegistrationModuleLogicPython(modulename);
}

