// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkSystemIncludes.h"
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings 

extern "C" void real_initvtkSlicerRegistrationModuleMRMLPython(const char *modulename);

extern  "C" { VTK_ABI_EXPORT void initvtkSlicerRegistrationModuleMRMLPython(); }

void initvtkSlicerRegistrationModuleMRMLPython()
{
  static const char modulename[] = "vtkSlicerRegistrationModuleMRMLPython";
  real_initvtkSlicerRegistrationModuleMRMLPython(modulename);
}

extern  "C" { VTK_ABI_EXPORT void initlibvtkSlicerRegistrationModuleMRMLPython(); }

void initlibvtkSlicerRegistrationModuleMRMLPython()
{
  static const char modulename[] = "libvtkSlicerRegistrationModuleMRMLPython";
  real_initvtkSlicerRegistrationModuleMRMLPython(modulename);
}

