
set(Slicer_CMAKE_DIR "/home/andreas/MyProjects/Slicer-r24735/CMake")
set(MIDAS_PACKAGE_URL "http://slicer.kitware.com/midas3")
set(MIDAS_PACKAGE_EMAIL "YOUR-MIDAS-LOGIN-NOTFOUND")
set(MIDAS_PACKAGE_API_KEY "YOUR-MIDAS-APIKEY-NOTFOUND")
set(CTEST_MODEL "Nightly")
set(Slicer_WC_REVISION "24735")
set(EXTENSION_NAME "Slicer-Featurelets")
set(EXTENSION_CATEGORY "Registration")
set(EXTENSION_ICONURL "http://www.example.com/Slicer/Extensions/Slicer-Featurelets.png")
set(EXTENSION_CONTRIBUTORS "Andreas Renner (Vienna UT)")
set(EXTENSION_DESCRIPTION "This Extension uses regularly distributed image subvolumes to achiev multimodal deformable registration.")
set(EXTENSION_HOMEPAGE "http://www.example.com/Slicer/Extensions/Slicer-Featurelets")
set(EXTENSION_SCREENSHOTURLS "http://www.example.com/Slicer/Extensions/Slicer-Featurelets/Screenshots/1.png")
set(EXTENSION_ENABLED "1")
set(EXTENSION_OPERATING_SYSTEM "linux")
set(EXTENSION_ARCHITECTURE "amd64")
set(EXTENSION_WC_TYPE "git")
set(EXTENSION_WC_URL "https://github.com/AndreasRenner/Slicer-Featurelets-Extension.git")
set(EXTENSION_WC_REVISION "ea503eb")
set(EXTENSION_BINARY_DIR "/home/andreas/code/Slicer-Featurelets_4.5/Slicer-Featurelets-build/.")