set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(GIT_EXECUTABLE "/usr/bin/git")
set(Subversion_SVN_EXECUTABLE "/usr/bin/svn")
set(CMAKE_MAKE_PROGRAM "/usr/bin/make")
set(CMAKE_C_COMPILER "/usr/bin/cc")
set(CMAKE_CXX_COMPILER "/usr/bin/c++")
set(BUILD_TESTING "ON")
set(RUN_CTEST_SUBMIT "TRUE")
set(EXTENSION_BUILD_OPTIONS_STRING "64bits-Qt4.8")
set(EXTENSION_COMPILER "g++")
set(EXTENSION_NAME "Slicer-Featurelets")
set(EXTENSION_CATEGORY "Registration")
set(EXTENSION_STATUS "")
set(EXTENSION_ICONURL "http://www.example.com/Slicer/Extensions/Slicer-Featurelets.png")
set(EXTENSION_CONTRIBUTORS "Andreas Renner (Vienna UT)")
set(EXTENSION_DESCRIPTION "This Extension uses regularly distributed image subvolumes to achiev multimodal deformable registration.")
set(EXTENSION_HOMEPAGE "http://www.example.com/Slicer/Extensions/Slicer-Featurelets")
set(EXTENSION_SCREENSHOTURLS "http://www.example.com/Slicer/Extensions/Slicer-Featurelets/Screenshots/1.png")
set(EXTENSION_SOURCE_DIR "/home/andreas/code/Slicer-Featurelets")
set(EXTENSION_SUPERBUILD_BINARY_DIR "/home/andreas/code/Slicer-Featurelets_4.5/Slicer-Featurelets-build")
set(EXTENSION_BUILD_SUBDIRECTORY ".")
set(EXTENSION_ENABLED "1")
set(EXTENSION_DEPENDS "NA")
set(Slicer_CMAKE_DIR "/home/andreas/MyProjects/Slicer-r24735/CMake")
set(Slicer_DIR "/home/andreas/Slicer-SuperBuild-Release_4.5/Slicer-build")
set(Slicer_EXTENSIONS_TRACK_QUALIFIER "master")
set(Slicer_WC_REVISION "24735")
set(MIDAS_PACKAGE_URL "http://slicer.kitware.com/midas3")
set(MIDAS_PACKAGE_EMAIL "YOUR-MIDAS-LOGIN-NOTFOUND")
set(MIDAS_PACKAGE_API_KEY "YOUR-MIDAS-APIKEY-NOTFOUND")
set(NA_DIR "")
set(RUN_CTEST_CONFIGURE "TRUE")
set(RUN_CTEST_BUILD "TRUE")
set(RUN_CTEST_TEST "TRUE")
set(RUN_CTEST_PACKAGES "TRUE")
set(RUN_CTEST_UPLOAD "FALSE")